name: windx1999
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  email_validator: ^3.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  curved_navigation_bar: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.6
  camera: ^0.11.1
  flutter_custom_clippers: ^2.1.0
  gradient_icon: ^2.0.9
  device_preview: ^1.2.0
  video_player: ^2.9.3
  http: ^1.3.0
  logger: ^2.5.0
  get_storage:
  mime: ^2.0.0
  http_parser: ^4.1.2
  webview_flutter: ^2.0.3
  file_picker: ^10.2.0
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/video/video.mp4

   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
          weight: 400
          
    
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
