class CountryData {
  static final Map<String, List<String>> countryStateMap = {
    'Afghanistan': [
      'Badakhshan',
      'Badghis',
      'Baghlan',
      'Balkh',
      'Bamyan',
      'Daykundi',
      'Farah',
      'Faryab',
      'Ghazni',
      'Ghor',
      'Helmand',
      'Herat',
      'Jowzjan',
      'Kabul',
      'Kandahar',
      'Kapisa',
      'Khost',
      'Kunar',
      'Kunduz',
      'Laghman',
      'Logar',
      'Nangarhar',
      'Nimruz',
      'Nuristan',
      'Paktia',
      'Paktika',
      'Panjshir',
      'Parwan',
      'Samangan',
      'Sar-e Pol',
      'Takhar',
      'Urozgan',
      'Wardak',
      'Zabul'
    ],
    'Albania': [
      'Berat',
      'Dibër',
      'Durrës',
      'Elbasan',
      'Fier',
      'Gjirokastër',
      'Korçë',
      'Kukës',
      'Lezhë',
      'Shkodër',
      'Tiranë',
      'Vlorë'
    ],
    'Algeria': [
      'Adrar',
      'Aïn Defla',
      'Aïn Témouchent',
      'Algiers',
      'Annaba',
      'Batna',
      'Béchar',
      'Béjaïa',
      'Béni Abbès',
      'Biskra',
      'Blida',
      'Bordj Badji Mokhtar',
      'Bordj Bou Arréridj',
      'Bouïra',
      'Boumerdès',
      'Chlef',
      'Constantine',
      'Djanet',
      'Djelfa',
      'El Bayadh',
      'El M’Ghair',
      'El Menia',
      'El Oued',
      'El Tarf',
      'Ghardaïa',
      'Guelma',
      'Illizi',
      'In Guezzam',
      'In Salah',
      'Jijel',
      'Khenchela',
      'Laghouat',
      'M’Sila',
      'Mascara',
      'Médéa',
      'Mila',
      'Mostaganem',
      'Naâma',
      'Oran',
      'Ouargla',
      'Oum El Bouaghi',
      'Relizane',
      'Saïda',
      'Sétif',
      'Sidi Bel Abbès',
      'Skikda',
      'Souk Ahras',
      'Tamanrasset',
      'Tébessa',
      'Tiaret',
      'Timimoun',
      'Tindouf',
      'Tipaza',
      'Tissemsilt',
      'Tizi Ouzou',
      'Tlemcen',
      'Touggourt'
    ],
    'Andorra': [
      'Andorra la Vella',
      'Canillo',
      'Encamp',
      'Escaldes-Engordany',
      'La Massana',
      'Ordino',
      'Sant Julià de Lòria'
    ],
    'Angola': [
      'Bengo',
      'Benguela',
      'Bié',
      'Cabinda',
      'Cuando Cubango',
      'Cuanza Norte',
      'Cuanza Sul',
      'Cunene',
      'Huambo',
      'Huíla',
      'Luanda',
      'Lunda Norte',
      'Lunda Sul',
      'Malanje',
      'Moxico',
      'Namibe',
      'Uíge',
      'Zaire'
    ],
    'Antigua and Barbuda': [
      'Barbuda',
      'Saint George',
      'Saint John',
      'Saint Mary',
      'Saint Paul',
      'Saint Peter',
      'Saint Philip'
    ],
    'Argentina': [
      'Buenos Aires',
      'Catamarca',
      'Chaco',
      'Chubut',
      'Córdoba',
      'Corrientes',
      'Entre Ríos',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquén',
      'Río Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucumán',
      'Ciudad Autónoma de Buenos Aires'
    ],
    'Armenia': [
      'Aragatsotn',
      'Ararat',
      'Armavir',
      'Gegharkunik',
      'Kotayk',
      'Lori',
      'Shirak',
      'Syunik',
      'Tavush',
      'Vayots Dzor',
      'Yerevan'
    ],
    'Australia': [
      'New South Wales',
      'Queensland',
      'South Australia',
      'Tasmania',
      'Victoria',
      'Western Australia',
      'Australian Capital Territory',
      'Northern Territory'
    ],
    'Austria': [
      'Burgenland',
      'Carinthia',
      'Lower Austria',
      'Upper Austria',
      'Salzburg',
      'Styria',
      'Tyrol',
      'Vorarlberg',
      'Vienna'
    ],
    'Azerbaijan': [
      'Absheron',
      'Aghjabadi',
      'Agdam',
      'Agdash',
      'Aghstafa',
      'Agsu',
      'Astara',
      'Baku',
      'Balakan',
      'Barda',
      'Beylagan',
      'Bilasuvar',
      'Dashkasan',
      'Fizuli',
      'Gadabay',
      'Ganja',
      'Gobustan',
      'Goychay',
      'Goygol',
      'Hajigabul',
      'Imishli',
      'Ismayilli',
      'Jabrayil',
      'Jalilabad',
      'Julfa',
      'Kalbajar',
      'Kangarli',
      'Khachmaz',
      'Khankendi',
      'Khizi',
      'Khojavend',
      'Kurdamir',
      'Lachin',
      'Lankaran',
      'Lerik',
      'Masally',
      'Mingachevir',
      'Naftalan',
      'Nakhchivan',
      'Neftchala',
      'Oghuz',
      'Qabala',
      'Qakh',
      'Qazakh',
      'Quba',
      'Qubadli',
      'Qusar',
      'Saatly',
      'Sabirabad',
      'Salyan',
      'Samukh',
      'Shaki',
      'Shamakhi',
      'Shamkir',
      'Sharur',
      'Shusha',
      'Siyazan',
      'Sumqayit',
      'Tartar',
      'Tovuz',
      'Ujar',
      'Yardimli',
      'Yevlakh',
      'Zangilan',
      'Zaqatala',
      'Zardab'
    ],
    'Bahamas': [
      'Acklins',
      'Berry Islands',
      'Bimini',
      'Black Point',
      'Cat Island',
      'Central Abaco',
      'Central Andros',
      'Central Eleuthera',
      'Crooked Island',
      'East Grand Bahama',
      'Exuma',
      'Freeport',
      'Grand Cay',
      'Harbour Island',
      'Hope Town',
      'Inagua',
      'Long Island',
      'Mangrove Cay',
      'Mayaguana',
      'Moore’s Island',
      'North Abaco',
      'North Andros',
      'North Eleuthera',
      'Ragged Island',
      'Rum Cay',
      'San Salvador',
      'South Abaco',
      'South Andros',
      'South Eleuthera',
      'Spanish Wells',
      'West Grand Bahama'
    ],
    'Bahrain': ['Capital', 'Muharraq', 'Northern', 'Southern'],
    'Bangladesh': [
      'Barisal',
      'Chattogram',
      'Dhaka',
      'Khulna',
      'Mymensingh',
      'Rajshahi',
      'Rangpur',
      'Sylhet'
    ],
    'Barbados': [
      'Christ Church',
      'Saint Andrew',
      'Saint George',
      'Saint James',
      'Saint John',
      'Saint Joseph',
      'Saint Lucy',
      'Saint Michael',
      'Saint Peter',
      'Saint Philip',
      'Saint Thomas'
    ],
    'Belarus': [
      'Brest',
      'Gomel',
      'Grodno',
      'Minsk',
      'Mogilev',
      'Vitebsk',
      'Minsk City'
    ],
    'Belgium': [
      'Antwerp',
      'East Flanders',
      'Flemish Brabant',
      'Limburg',
      'West Flanders',
      'Hainaut',
      'Liège',
      'Luxembourg',
      'Namur',
      'Walloon Brabant',
      'Brussels-Capital'
    ],
    'Belize': [
      'Belize',
      'Cayo',
      'Corozal',
      'Orange Walk',
      'Stann Creek',
      'Toledo'
    ],
    'Benin': [
      'Alibori',
      'Atakora',
      'Atlantique',
      'Borgou',
      'Collines',
      'Couffo',
      'Donga',
      'Littoral',
      'Mono',
      'Ouémé',
      'Plateau',
      'Zou'
    ],
    'Bhutan': [
      'Bumthang',
      'Chhukha',
      'Dagana',
      'Gasa',
      'Haa',
      'Lhuentse',
      'Mongar',
      'Paro',
      'Pemagatshel',
      'Punakha',
      'Samdrup Jongkhar',
      'Samtse',
      'Sarpang',
      'Thimphu',
      'Trashigang',
      'Trashiyangtse',
      'Trongsa',
      'Tsirang',
      'Wangdue Phodrang',
      'Zhemgang'
    ],
    'Bolivia': [
      'Beni',
      'Chuquisaca',
      'Cochabamba',
      'La Paz',
      'Oruro',
      'Pando',
      'Potosí',
      'Santa Cruz',
      'Tarija'
    ],
    'Bosnia and Herzegovina': [
      'Federation of Bosnia and Herzegovina',
      'Republika Srpska',
      'Brčko District'
    ],
    'Botswana': [
      'Central',
      'Chobe',
      'Ghanzi',
      'Kgalagadi',
      'Kgatleng',
      'Kweneng',
      'North-East',
      'North-West',
      'South-East',
      'Southern'
    ],
    'Brazil': [
      'Acre',
      'Alagoas',
      'Amapá',
      'Amazonas',
      'Bahia',
      'Ceará',
      'Espírito Santo',
      'Goiás',
      'Maranhão',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Pará',
      'Paraíba',
      'Paraná',
      'Pernambuco',
      'Piauí',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondônia',
      'Roraima',
      'Santa Catarina',
      'São Paulo',
      'Sergipe',
      'Tocantins',
      'Distrito Federal'
    ],
    'Brunei': ['Belait', 'Brunei-Muara', 'Temburong', 'Tutong'],
    'Bulgaria': [
      'Blagoevgrad',
      'Burgas',
      'Dobrich',
      'Gabrovo',
      'Haskovo',
      'Kardzhali',
      'Kyustendil',
      'Lovech',
      'Montana',
      'Pazardzhik',
      'Pernik',
      'Pleven',
      'Plovdiv',
      'Razgrad',
      'Ruse',
      'Shumen',
      'Silistra',
      'Sliven',
      'Smolyan',
      'Sofia',
      'Sofia-City',
      'Stara Zagora',
      'Targovishte',
      'Varna',
      'Veliko Tarnovo',
      'Vidin',
      'Vratsa',
      'Yambol'
    ],
    'Burkina Faso': [
      'Balé',
      'Bam',
      'Banwa',
      'Bazèga',
      'Bougouriba',
      'Boulgou',
      'Boulkiemdé',
      'Comoé',
      'Ganzourgou',
      'Gnagna',
      'Gourma',
      'Houet',
      'Ioba',
      'Kadiogo',
      'Kénédougou',
      'Komondjari',
      'Kompienga',
      'Kossi',
      'Koulpélogo',
      'Kouritenga',
      'Kourwéogo',
      'Léraba',
      'Loroum',
      'Mouhoun',
      'Nahouri',
      'Namentenga',
      'Nayala',
      'Noumbiel',
      'Oubritenga',
      'Oudalan',
      'Passoré',
      'Poni',
      'Sanguié',
      'Sanmatenga',
      'Seno',
      'Sissili',
      'Soum',
      'Sourou',
      'Tapoa',
      'Tuy',
      'Yagha',
      'Yatenga',
      'Ziro',
      'Zondoma',
      'Zoundwéogo'
    ],
    'Burundi': [
      'Bubanza',
      'Bujumbura Mairie',
      'Bujumbura Rural',
      'Bururi',
      'Cankuzo',
      'Cibitoke',
      'Gitega',
      'Karuzi',
      'Kayanza',
      'Kirundo',
      'Makamba',
      'Muramvya',
      'Muyinga',
      'Mwaro',
      'Ngozi',
      'Rumonge',
      'Rutana',
      'Ruyigi'
    ],
    'Cambodia': [
      'Banteay Meanchey',
      'Battambang',
      'Kampong Cham',
      'Kampong Chhnang',
      'Kampong Speu',
      'Kampong Thom',
      'Kampot',
      'Kandal',
      'Koh Kong',
      'Kratié',
      'Mondulkiri',
      'Oddar Meanchey',
      'Pailin',
      'Phnom Penh',
      'Preah Vihear',
      'Prey Veng',
      'Pursat',
      'Ratanakiri',
      'Siem Reap',
      'Sihanoukville',
      'Stung Treng',
      'Svay Rieng',
      'Takéo',
      'Tboung Khmum'
    ],
    'Cameroon': [
      'Adamawa',
      'Centre',
      'East',
      'Far North',
      'Littoral',
      'North',
      'North-West',
      'South',
      'South-West',
      'West'
    ],
    'Canada': [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Newfoundland and Labrador',
      'Nova Scotia',
      'Ontario',
      'Prince Edward Island',
      'Quebec',
      'Saskatchewan',
      'Northwest Territories',
      'Nunavut',
      'Yukon'
    ],
    'Cape Verde': [
      'Boa Vista',
      'Brava',
      'Maio',
      'Mosteiros',
      'Paul',
      'Porto Novo',
      'Praia',
      'Ribeira Brava',
      'Ribeira Grande',
      'Ribeira Grande de Santiago',
      'Sal',
      'Santa Catarina',
      'Santa Catarina do Fogo',
      'Santa Cruz',
      'São Domingos',
      'São Filipe',
      'São Lourenço dos Órgãos',
      'São Miguel',
      'São Salvador do Mundo',
      'São Vicente',
      'Tarrafal',
      'Tarrafal de São Nicolau'
    ],
    'Central African Republic': [
      'Bamingui-Bangoran',
      'Bangui',
      'Basse-Kotto',
      'Haut-Mbomou',
      'Haute-Kotto',
      'Kémo',
      'Lobaye',
      'Mambéré-Kadéï',
      'Mbomou',
      'Nana-Grébizi',
      'Nana-Mambéré',
      'Ombella-M’Poko',
      'Ouaka',
      'Ouham',
      'Ouham-Pendé',
      'Sangha-Mbaéré',
      'Vakaga'
    ],
    'Chad': [
      'Barh El Gazel',
      'Batha',
      'Borkou',
      'Chari-Baguirmi',
      'Ennedi-Est',
      'Ennedi-Ouest',
      'Guéra',
      'Hadjer-Lamis',
      'Kanem',
      'Lac',
      'Logone Occidental',
      'Logone Oriental',
      'Mandoul',
      'Mayo-Kebbi Est',
      'Mayo-Kebbi Ouest',
      'Moyen-Chari',
      'Ndjamena',
      'Ouaddaï',
      'Salamat',
      'Sila',
      'Tandjilé',
      'Tibesti',
      'Wadi Fira'
    ],
    'Chile': [
      'Aisén',
      'Antofagasta',
      'Araucanía',
      'Arica y Parinacota',
      'Atacama',
      'Biobío',
      'Coquimbo',
      'Los Lagos',
      'Los Ríos',
      'Magallanes',
      'Maule',
      'Ñuble',
      'O’Higgins',
      'Santiago',
      'Tarapacá',
      'Valparaíso'
    ],
    'China': [
      'Anhui',
      'Fujian',
      'Gansu',
      'Guangdong',
      'Guizhou',
      'Hainan',
      'Hebei',
      'Heilongjiang',
      'Henan',
      'Hubei',
      'Hunan',
      'Jiangsu',
      'Jiangxi',
      'Jilin',
      'Liaoning',
      'Qinghai',
      'Shaanxi',
      'Shandong',
      'Shanxi',
      'Sichuan',
      'Yunnan',
      'Zhejiang',
      'Guangxi',
      'Inner Mongolia',
      'Ningxia',
      'Xinjiang',
      'Tibet',
      'Beijing',
      'Chongqing',
      'Shanghai',
      'Tianjin',
      'Hong Kong',
      'Macau'
    ],
    'Colombia': [
      'Amazonas',
      'Antioquia',
      'Arauca',
      'Atlántico',
      'Bolívar',
      'Boyacá',
      'Caldas',
      'Caquetá',
      'Casanare',
      'Cauca',
      'Cesar',
      'Chocó',
      'Córdoba',
      'Cundinamarca',
      'Guainía',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Nariño',
      'Norte de Santander',
      'Putumayo',
      'Quindío',
      'Risaralda',
      'San Andrés y Providencia',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupés',
      'Vichada',
      'Bogotá'
    ],
    'Comoros': ['Anjouan', 'Grande Comore', 'Mohéli'],
    'Costa Rica': [
      'Alajuela',
      'Cartago',
      'Guanacaste',
      'Heredia',
      'Limón',
      'Puntarenas',
      'San José'
    ],
    'Croatia': [
      'Bjelovar-Bilogora',
      'Brod-Posavina',
      'Dubrovnik-Neretva',
      'Istria',
      'Karlovac',
      'Koprivnica-Križevci',
      'Krapina-Zagorje',
      'Lika-Senj',
      'Međimurje',
      'Osijek-Baranja',
      'Požega-Slavonia',
      'Primorje-Gorski Kotar',
      'Šibenik-Knin',
      'Sisak-Moslavina',
      'Split-Dalmatia',
      'Varaždin',
      'Virovitica-Podravina',
      'Vukovar-Syrmia',
      'Zadar',
      'Zagreb',
      'Zagreb City'
    ],
    'Cuba': [
      'Artemisa',
      'Camagüey',
      'Ciego de Ávila',
      'Cienfuegos',
      'Granma',
      'Guantánamo',
      'Holguín',
      'Isla de la Juventud',
      'La Habana',
      'Las Tunas',
      'Matanzas',
      'Mayabeque',
      'Pinar del Río',
      'Sancti Spíritus',
      'Santiago de Cuba',
      'Villa Clara'
    ],
    'Cyprus': [
      'Famagusta',
      'Kyrenia',
      'Larnaca',
      'Limassol',
      'Nicosia',
      'Paphos'
    ],
    'Czech Republic': [
      'Central Bohemian',
      'Hradec Králové',
      'Karlovy Vary',
      'Liberec',
      'Moravian-Silesian',
      'Olomouc',
      'Pardubice',
      'Plzeň',
      'Prague',
      'South Bohemian',
      'South Moravian',
      'Ústí nad Labem',
      'Vysočina',
      'Zlín'
    ],
    'Democratic Republic of the Congo': [
      'Bas-Uélé',
      'Équateur',
      'Haut-Katanga',
      'Haut-Lomami',
      'Haut-Uélé',
      'Ituri',
      'Kasaï',
      'Kasaï-Central',
      'Kasaï-Oriental',
      'Kinshasa',
      'Kongo Central',
      'Kwango',
      'Kwilu',
      'Lomami',
      'Lualaba',
      'Mai-Ndombe',
      'Maniema',
      'Mongala',
      'Nord-Kivu',
      'Nord-Ubangi',
      'Sankuru',
      'Sud-Kivu',
      'Sud-Ubangi',
      'Tanganyika',
      'Tshopo',
      'Tshuapa'
    ],
    'Denmark': [
      'Capital',
      'Central Montana',
      'North Montana',
      'Zealand',
      'Southern Montana'
    ],
    'Djibouti': [
      'Ali Sabieh',
      'Arta',
      'Dikhil',
      'Djibouti',
      'Obock',
      'Tadjourah'
    ],
    'Dominica': [
      'Saint Andrew',
      'Saint David',
      'Saint George',
      'Saint John',
      'Saint Joseph',
      'Saint Luke',
      'Saint Mark',
      'Saint Patrick',
      'Saint Paul',
      'Saint Peter'
    ],
    'Dominican Republic': [
      'Azua',
      'Baoruco',
      'Barahona',
      'Dajabón',
      'Distrito Nacional',
      'Duarte',
      'El Seibo',
      'Elías Piña',
      'Espaillat',
      'Hato Mayor',
      'Hermanas Mirabal',
      'Independencia',
      'La Altagracia',
      'La Romana',
      'La Vega',
      'María Trinidad Sánchez',
      'Monseñor Nouel',
      'Monte Cristi',
      'Monte Plata',
      'Pedernales',
      'Peravia',
      'Puerto Plata',
      'Samaná',
      'San Cristóbal',
      'San José de Ocoa',
      'San Juan',
      'San Pedro de Macorís',
      'Sánchez Ramírez',
      'Santiago',
      'Santiago Rodríguez',
      'Santo Domingo',
      'Valverde'
    ],
    'Ecuador': [
      'Azuay',
      'Bolívar',
      'Cañar',
      'Carchi',
      'Chimborazo',
      'Cotopaxi',
      'El Oro',
      'Esmeraldas',
      'Galápagos',
      'Guayas',
      'Imbabura',
      'Loja',
      'Los Ríos',
      'Manabí',
      'Morona-Santiago',
      'Napo',
      'Orellana',
      'Pastaza',
      'Pichincha',
      'Santa Elena',
      'Santo Domingo de los Tsáchilas',
      'Sucumbíos',
      'Tungurahua',
      'Zamora-Chinchipe'
    ],
    'Egypt': [
      'Alexandria',
      'Aswan',
      'Asyut',
      'Beheira',
      'Beni Suef',
      'Cairo',
      'Dakahlia',
      'Damietta',
      'Faiyum',
      'Gharbia',
      'Giza',
      'Ismailia',
      'Kafr El Sheikh',
      'Luxor',
      'Matruh',
      'Minya',
      'Monufia',
      'New Valley',
      'North Sinai',
      'Port Said',
      'Qalyubia',
      'Qena',
      'Red Sea',
      'Sharqia',
      'Sohag',
      'South Sinai',
      'Suez'
    ],
    'El Salvador': [
      'Ahuachapán',
      'Cabañas',
      'Chalatenango',
      'Cuscatlán',
      'La Libertad',
      'La Paz',
      'La Unión',
      'Morazán',
      'San Miguel',
      'San Salvador',
      'San Vicente',
      'Santa Ana',
      'Sonsonate',
      'Usulután'
    ],
    'Equatorial Guinea': [
      'Annobón',
      'Bioko Norte',
      'Bioko Sur',
      'Centro Sur',
      'Kié-Ntem',
      'Litoral',
      'Wele-Nzas'
    ],
    'Eritrea': [
      'Anseba',
      'Debub',
      'Gash-Barka',
      'Maekel',
      'Northern Red Sea',
      'Southern Red Sea'
    ],
    'Estonia': [
      'Harju',
      'Hiiu',
      'Ida-Viru',
      'Järva',
      'Jõgeva',
      'Lääne',
      'Lääne-Viru',
      'Pärnu',
      'Põlva',
      'Rapla',
      'Saare',
      'Tartu',
      'Valga',
      'Viljandi',
      'Võru'
    ],
    'Eswatini': ['Hhohho', 'Lubombo', 'Manzini', 'Shiselweni'],
    'Ethiopia': [
      'Addis Ababa',
      'Afar',
      'Amhara',
      'Benishangul-Gumuz',
      'Dire Dawa',
      'Gambela',
      'Harari',
      'Oromia',
      'Sidama',
      'Somali',
      'South West Ethiopia Peoples',
      'Southern Nations, Nationalities, and Peoples',
      'Tigray'
    ],
    'Fiji': [
      'Ba',
      'Bua',
      'Cakaudrove',
      'Kadavu',
      'Lau',
      'Lomaiviti',
      'Macuata',
      'Nadroga-Navosa',
      'Naitasiri',
      'Namosi',
      'Ra',
      'Rewa',
      'Serua',
      'Tailevu',
      'Rotuma'
    ],
    'Finland': [
      'Åland',
      'Central Finland',
      'Central Ostrobothnia',
      'Kainuu',
      'Kymenlaakso',
      'Lapland',
      'North Karelia',
      'Northern Ostrobothnia',
      'Northern Savonia',
      'Ostrobothnia',
      'Päijänne Tavastia',
      'Pirkanmaa',
      'Satakunta',
      'South Karelia',
      'Southern Ostrobothnia',
      'Southern Savonia',
      'Southwest Finland',
      'Tavastia Proper',
      'Uusimaa'
    ],
    'France': [
      'Auvergne-Rhône-Alpes',
      'Bourgogne-Franche-Comté',
      'Brittany',
      'Centre-Val de Loire',
      'Corsica',
      'Grand Est',
      'Hauts-de-France',
      'Île-de-France',
      'Normandy',
      'Nouvelle-Aquitaine',
      'Occitanie',
      'Pays de la Loire',
      'Provence-Alpes-Côte d’Azur',
      'Guadeloupe',
      'French Guiana',
      'Martinique',
      'Mayotte',
      'Réunion'
    ],
    'Gabon': [
      'Estuaire',
      'Haut-Ogooué',
      'Moyen-Ogooué',
      'Ngounié',
      'Nyanga',
      'Ogooué-Ivindo',
      'Ogooué-Lolo',
      'Ogooué-Maritime',
      'Woleu-Ntem'
    ],
    'Gambia': [
      'Banjul',
      'Central River',
      'Lower River',
      'North Bank',
      'Upper River',
      'West Coast'
    ],
    'Georgia': [
      'Abkhazia',
      'Adjara',
      'Guria',
      'Imereti',
      'Kakheti',
      'Kvemo Kartli',
      'Mtskheta-Mtianeti',
      'Racha-Lechkhumi and Kvemo Svaneti',
      'Samegrelo-Zemo Svaneti',
      'Samtskhe-Javakheti',
      'Shida Kartli',
      'Tbilisi'
    ],
    'Germany': [
      'Baden-Württemberg',
      'Bavaria',
      'Berlin',
      'Brandenburg',
      'Bremen',
      'Hamburg',
      'Hesse',
      'Lower Saxony',
      'Mecklenburg-Vorpommern',
      'North Rhine-Westphalia',
      'Rhineland-Palatinate',
      'Saarland',
      'Saxony',
      'Saxony-Anhalt',
      'Schleswig-Holstein',
      'Thuringia'
    ],
    'Ghana': [
      'Ahafo',
      'Ashanti',
      'Bono',
      'Bono East',
      'Central',
      'Eastern',
      'Greater Accra',
      'North East',
      'Northern',
      'Oti',
      'Savannah',
      'Upper East',
      'Upper West',
      'Volta',
      'Western',
      'Western North'
    ],
    'Greece': [
      'Attica',
      'Central Greece',
      'Central Macedonia',
      'Crete',
      'Eastern Macedonia and Thrace',
      'Epirus',
      'Ionian Islands',
      'North Aegean',
      'Peloponnese',
      'South Aegean',
      'Thessaly',
      'Western Greece',
      'Western Macedonia',
      'Mount Athos'
    ],
    'Grenada': [
      'Carriacou and Petite Martinique',
      'Saint Andrew',
      'Saint David',
      'Saint George',
      'Saint John',
      'Saint Mark',
      'Saint Patrick'
    ],
    'Guatemala': [
      'Alta Verapaz',
      'Baja Verapaz',
      'Chimaltenango',
      'Chiquimula',
      'El Progreso',
      'Escuintla',
      'Guatemala',
      'Huehuetenango',
      'Izabal',
      'Jalapa',
      'Jutiapa',
      'Petén',
      'Quetzaltenango',
      'Quiché',
      'Retalhuleu',
      'Sacatepéquez',
      'San Marcos',
      'Santa Rosa',
      'Sololá',
      'Suchitepéquez',
      'Totonicapán',
      'Zacapa'
    ],
    'Guinea': [
      'Boké',
      'Conakry',
      'Faranah',
      'Kankan',
      'Kindia',
      'Labé',
      'Mamou',
      'Nzérékoré'
    ],
    'Guinea-Bissau': [
      'Bafatá',
      'Biombo',
      'Bissau',
      'Bolama',
      'Cacheu',
      'Gabú',
      'Oio',
      'Quinara',
      'Tombali'
    ],
    'Guyana': [
      'Barima-Waini',
      'Cuyuni-Mazaruni',
      'Demerara-Mahaica',
      'East Berbice-Corentyne',
      'Essequibo Islands-West Demerara',
      'Mahaica-Berbice',
      'Pomeroon-Supenaam',
      'Potaro-Siparuni',
      'Upper Demerara-Berbice',
      'Upper Takutu-Upper Essequibo'
    ],
    'Haiti': [
      'Artibonite',
      'Centre',
      'Grand’Anse',
      'Nippes',
      'Nord',
      'Nord-Est',
      'Nord-Ouest',
      'Ouest',
      'Sud',
      'Sud-Est'
    ],
    'Honduras': [
      'Atlántida',
      'Choluteca',
      'Colón',
      'Comayagua',
      'Copán',
      'Cortés',
      'El Paraíso',
      'Francisco Morazán',
      'Gracias a Dios',
      'Intibucá',
      'Islas de la Bahía',
      'La Paz',
      'Lempira',
      'Ocotepeque',
      'Olancho',
      'Santa Bárbara',
      'Valle',
      'Yoro'
    ],
    'Hungary': [
      'Bács-Kiskun',
      'Baranya',
      'Békés',
      'Borsod-Abaúj-Zemplén',
      'Budapest',
      'Csongrád-Csanád',
      'Fejér',
      'Győr-Moson-Sopron',
      'Hajdú-Bihar',
      'Heves',
      'Jász-Nagykun-Szolnok',
      'Komárom-Esztergom',
      'Nógrád',
      'Pest',
      'Somogy',
      'Szabolcs-Szatmár-Bereg',
      'Tolna',
      'Vas',
      'Veszprém',
      'Zala'
    ],
    'Iceland': [
      'Capital Region',
      'Southern Peninsula',
      'Western Region',
      'Westfjords',
      'Northwestern Region',
      'Northeastern Region',
      'Eastern Region',
      'Southern Region'
    ],
    'India': [
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chhattisgarh',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal',
      'Andaman and Nicobar Islands',
      'Chandigarh',
      'Dadra and Nagar Haveli and Daman and Diu',
      'Delhi',
      'Jammu and Kashmir',
      'Ladakh',
      'Lakshadweep',
      'Puducherry'
    ],
    'Indonesia': [
      'Aceh',
      'Bali',
      'Bangka Belitung',
      'Banten',
      'Bengkulu',
      'Central Java',
      'Central Kalimantan',
      'Central Sulawesi',
      'East Java',
      'East Kalimantan',
      'East Nusa Tenggara',
      'Gorontalo',
      'Jakarta',
      'Jambi',
      'Lampung',
      'Maluku',
      'North Kalimantan',
      'North Maluku',
      'North Sulawesi',
      'North Sumatra',
      'Papua',
      'Riau',
      'Riau Islands',
      'South Kalimantan',
      'South Sulawesi',
      'South Sumatra',
      'Southeast Sulawesi',
      'West Java',
      'West Kalimantan',
      'West Nusa Tenggara',
      'West Papua',
      'West Sulawesi',
      'West Sumatra',
      'Yogyakarta'
    ],
    'Iran': [
      'Alborz',
      'Ardabil',
      'Bushehr',
      'Chaharmahal and Bakhtiari',
      'East Azerbaijan',
      'Fars',
      'Gilan',
      'Golestan',
      'Hamadan',
      'Hormozgan',
      'Ilam',
      'Isfahan',
      'Kerman',
      'Kermanshah',
      'Khuzestan',
      'Kohgiluyeh and Boyer-Ahmad',
      'Kurdistan',
      'Lorestan',
      'Markazi',
      'Mazandaran',
      'North Khorasan',
      'Qazvin',
      'Qom',
      'Razavi Khorasan',
      'Semnan',
      'Sistan and Baluchestan',
      'South Khorasan',
      'Tehran',
      'West Azerbaijan',
      'Yazd',
      'Zanjan'
    ],
    'Iraq': [
      'Al Anbar',
      'Al Muthanna',
      'Al Qadisiyah',
      'An Najaf',
      'Arbil',
      'Babil',
      'Baghdad',
      'Basra',
      'Dhi Qar',
      'Diyala',
      'Dohuk',
      'Karbala',
      'Kirkuk',
      'Maysan',
      'Nineveh',
      'Saladin',
      'Sulaymaniyah',
      'Wasit'
    ],
    'Ireland': [
      'Carlow',
      'Cavan',
      'Clare',
      'Cork',
      'Donegal',
      'Dublin',
      'Galway',
      'Kerry',
      'Kildare',
      'Kilkenny',
      'Laois',
      'Leitrim',
      'Limerick',
      'Longford',
      'Louth',
      'Mayo',
      'Meath',
      'Monaghan',
      'Offaly',
      'Roscommon',
      'Sligo',
      'Tipperary',
      'Waterford',
      'Westmeath',
      'Wexford',
      'Wicklow'
    ],
    'Israel': [
      'Central',
      'Haifa',
      'Jerusalem',
      'Northern',
      'Southern',
      'Tel Aviv'
    ],
    'Italy': [
      'Abruzzo',
      'Aosta Valley',
      'Apulia',
      'Basilicata',
      'Calabria',
      'Campania',
      'Emilia-Romagna',
      'Friuli-Venezia Giulia',
      'Lazio',
      'Liguria',
      'Lombardy',
      'Marche',
      'Molise',
      'Piedmont',
      'Sardinia',
      'Sicily',
      'Trentino-South Tyrol',
      'Tuscany',
      'Umbria',
      'Veneto'
    ],
    'Ivory Coast': [
      'Abidjan',
      'Bas-Sassandra',
      'Comoé',
      'Denguélé',
      'Gôh-Djiboua',
      'Lacs',
      'Lagunes',
      'Montagnes',
      'Sassandra-Marahoué',
      'Savanes',
      'Vallée du Bandama',
      'Woroba',
      'Yamoussoukro',
      'Zanzan'
    ],
    'Jamaica': [
      'Clarendon',
      'Hanover',
      'Kingston',
      'Manchester',
      'Portland',
      'Saint Andrew',
      'Saint Ann',
      'Saint Catherine',
      'Saint Elizabeth',
      'Saint James',
      'Saint Mary',
      'Saint Thomas',
      'Trelawny',
      'Westmoreland'
    ],
    'Japan': [
      'Aichi',
      'Akita',
      'Aomori',
      'Chiba',
      'Ehime',
      'Fukui',
      'Fukuoka',
      'Fukushima',
      'Gifu',
      'Gunma',
      'Hiroshima',
      'Hokkaido',
      'Hyogo',
      'Ibaraki',
      'Ishikawa',
      'Iwate',
      'Kagawa',
      'Kagoshima',
      'Kanagawa',
      'Kochi',
      'Kumamoto',
      'Kyoto',
      'Mie',
      'Miyagi',
      'Miyazaki',
      'Nagano',
      'Nagasaki',
      'Nara',
      'Niigata',
      'Oita',
      'Okayama',
      'Okinawa',
      'Osaka',
      'Saga',
      'Saitama',
      'Shiga',
      'Shimane',
      'Shizuoka',
      'Tochigi',
      'Tokushima',
      'Tokyo',
      'Tottori',
      'Toyama',
      'Wakayama',
      'Yamagata',
      'Yamaguchi',
      'Yamanashi'
    ],
    'Jordan': [
      'Ajloun',
      'Amman',
      'Aqaba',
      'Balqa',
      'Irbid',
      'Jerash',
      'Karak',
      'Ma’an',
      'Madaba',
      'Mafraq',
      'Tafilah',
      'Zarqa'
    ],
    'Kazakhstan': [
      'Abai',
      'Akmola',
      'Aktobe',
      'Almaty',
      'Atyrau',
      'East Kazakhstan',
      'Jambyl',
      'Jetisu',
      'Karaganda',
      'Kostanay',
      'Kyzylorda',
      'Mangystau',
      'North Kazakhstan',
      'Pavlodar',
      'Turkistan',
      'West Kazakhstan',
      'Almaty City',
      'Astana',
      'Shymkent'
    ],
    'Kenya': [
      'Baringo',
      'Bomet',
      'Bungoma',
      'Busia',
      'Elgeyo-Marakwet',
      'Embu',
      'Garissa',
      'Homa Bay',
      'Isiolo',
      'Kajiado',
      'Kakamega',
      'Kericho',
      'Kiambu',
      'Kilifi',
      'Kirinyaga',
      'Kisii',
      'Kisumu',
      'Kitui',
      'Kwale',
      'Laikipia',
      'Lamu',
      'Machakos',
      'Makueni',
      'Mandera',
      'Marsabit',
      'Meru',
      'Migori',
      'Mombasa',
      'Murang’a',
      'Nairobi',
      'Nakuru',
      'Nandi',
      'Narok',
      'Nyamira',
      'Nyandarua',
      'Nyeri',
      'Samburu',
      'Siaya',
      'Taita-Taveta',
      'Tana River',
      'Tharaka-Nithi',
      'Trans Nzoia',
      'Turkana',
      'Uasin Gishu',
      'Vihiga',
      'Wajir',
      'West Pokot'
    ],
    'Kiribati': [], // No first-level administrative divisions
    'Kuwait': [
      'Al Ahmadi',
      'Al Asimah',
      'Al Farwaniyah',
      'Al Jahra',
      'Hawalli',
      'Mubarak Al-Kabeer'
    ],
    'Kyrgyzstan': [
      'Batken',
      'Bishkek',
      'Chuy',
      'Jalal-Abad',
      'Naryn',
      'Osh',
      'Osh City',
      'Talas',
      'Ysyk-Kol'
    ],
    'Laos': [
      'Attapeu',
      'Bokeo',
      'Bolikhamxai',
      'Champasak',
      'Houaphan',
      'Khammouane',
      'Luang Namtha',
      'Luang Prabang',
      'Oudomxay',
      'Phongsaly',
      'Salavan',
      'Savannakhet',
      'Vientiane',
      'Vientiane Prefecture',
      'Xaisomboun',
      'Xekong',
      'Xiangkhouang'
    ],
    'Latvia': [
      'Aizkraukle',
      'Alūksne',
      'Augšdaugava',
      'Balvi',
      'Bauska',
      'Cēsis',
      'Daugavpils',
      'Daugavpils City',
      'Dobele',
      'Gulbene',
      'Jēkabpils',
      'Jelgava',
      'Jelgava City',
      'Krāslava',
      'Kuldīga',
      'Liepāja',
      'Liepāja City',
      'Limbaži',
      'Ludza',
      'Madona',
      'Mārupe',
      'Ogre',
      'Olaine',
      'Preiļi',
      'Rēzekne',
      'Rēzekne City',
      'Rīga',
      'Rīga City',
      'Saldus',
      'Sigulda',
      'Smiltene',
      'Talsi',
      'Tukums',
      'Valka',
      'Valmiera',
      'Ventspils',
      'Ventspils City'
    ],
    'Lebanon': [
      'Akkar',
      'Baalbek-Hermel',
      'Beirut',
      'Beqaa',
      'Mount Lebanon',
      'Nabatieh',
      'North',
      'South'
    ],
    'Lesotho': [
      'Berea',
      'Butha-Buthe',
      'Leribe',
      'Mafeteng',
      'Maseru',
      'Mohale’s Hoek',
      'Mokhotlong',
      'Qacha’s Nek',
      'Quthing',
      'Thaba-Tseka'
    ],
    'Liberia': [
      'Bomi',
      'Bong',
      'Gbarpolu',
      'Grand Bassa',
      'Grand Cape Mount',
      'Grand Gedeh',
      'Grand Kru',
      'Lofa',
      'Margibi',
      'Maryland',
      'Montserrado',
      'Nimba',
      'River Cess',
      'River Gee',
      'Sinoe'
    ],
    'Libya': [
      'Al Butnan',
      'Al Jabal al Akhdar',
      'Al Jabal al Gharbi',
      'Al Jufrah',
      'Al Kufrah',
      'Al Marj',
      'Al Marqab',
      'Al Wahat',
      'Benghazi',
      'Darnah',
      'Ghat',
      'Misrata',
      'Murzuq',
      'Nalut',
      'Sabha',
      'Sirte',
      'Tripoli',
      'Wadi al Hayaa',
      'Wadi al Shatii',
      'Zawiya'
    ],
    'Liechtenstein': [
      'Balzers',
      'Eschen',
      'Gamprin',
      'Mauren',
      'Planken',
      'Ruggell',
      'Schaan',
      'Schellenberg',
      'Triesen',
      'Triesenberg',
      'Vaduz'
    ],
    'Lithuania': [
      'Alytus',
      'Kaunas',
      'Klaipėda',
      'Marijampolė',
      'Panevėžys',
      'Šiauliai',
      'Tauragė',
      'Telšiai',
      'Utena',
      'Vilnius'
    ],
    'Luxembourg': [], // No first-level administrative divisions
    'Madagascar': [
      'Amoron’i Mania',
      'Analamanga',
      'Analanjirofo',
      'Androy',
      'Anosy',
      'Atsinanana',
      'Atsimo-Andrefana',
      'Atsimo-Atsinanana',
      'Betsiboka',
      'Boeny',
      'Bongolava',
      'Diana',
      'Haute Matsiatra',
      'Ihorombe',
      'Itasy',
      'Melaky',
      'Menabe',
      'Sava',
      'Sofia',
      'Vakinankaratra',
      'Vatovavy',
      'Fitovinany'
    ],
    'Malawi': [
      'Balaka',
      'Blantyre',
      'Chikwawa',
      'Chiradzulu',
      'Chitipa',
      'Dedza',
      'Dowa',
      'Karonga',
      'Kasungu',
      'Likoma',
      'Lilongwe',
      'Machinga',
      'Mangochi',
      'Mchinji',
      'Mulanje',
      'Mwanza',
      'Mzimba',
      'Neno',
      'Nkhata Bay',
      'Nkhotakota',
      'Nsanje',
      'Ntcheu',
      'Ntchisi',
      'Phalombe',
      'Rumphi',
      'Salima',
      'Thyolo',
      'Zomba'
    ],
    'Malaysia': [
      'Johor',
      'Kedah',
      'Kelantan',
      'Kuala Lumpur',
      'Labuan',
      'Malacca',
      'Negeri Sembilan',
      'Pahang',
      'Penang',
      'Perak',
      'Perlis',
      'Putrajaya',
      'Sabah',
      'Sarawak',
      'Selangor',
      'Terengganu'
    ],
    'Maldives': [
      'Alif Alif',
      'Alif Dhaal',
      'Baa',
      'Dhaalu',
      'Faafu',
      'Gaafu Alif',
      'Gaafu Dhaal',
      'Gnaviyani',
      'Haa Alif',
      'Haa Dhaal',
      'Kaafu',
      'Laamu',
      'Lhaviyani',
      'Meemu',
      'Noonu',
      'Raa',
      'Seenu',
      'Shaviyani',
      'Thaa',
      'Vaavu'
    ],
    'Mali': [
      'Bamako',
      'Gao',
      'Kayes',
      'Kidal',
      'Koulikoro',
      'Ménaka',
      'Mopti',
      'Ségou',
      'Sikasso',
      'Taoudénit',
      'Tombouctou'
    ],
    'Malta': [
      'Attard',
      'Balzan',
      'Birgu',
      'Birkirkara',
      'Birżebbuġa',
      'Bormla',
      'Dingli',
      'Fgura',
      'Floriana',
      'Fontana',
      'Għajnsielem',
      'Għarb',
      'Għargħur',
      'Għasri',
      'Għaxaq',
      'Gudja',
      'Gżira',
      'Ħamrun',
      'Iklin',
      'Isla',
      'Kalkara',
      'Kerċem',
      'Kirkop',
      'Lija',
      'Luqa',
      'Marsa',
      'Marsaskala',
      'Marsaxlokk',
      'Mdina',
      'Mellieħa',
      'Mġarr',
      'Mosta',
      'Mqabba',
      'Msida',
      'Mtarfa',
      'Munxar',
      'Nadur',
      'Naxxar',
      'Paola',
      'Pembroke',
      'Pietà',
      'Qala',
      'Qormi',
      'Qrendi',
      'Rabat Gozo',
      'Rabat Malta',
      'Safi',
      'San Ġiljan',
      'San Ġwann',
      'San Lawrenz',
      'San Pawl il-Baħar',
      'Sannat',
      'Santa Luċija',
      'Santa Venera',
      'Siġġiewi',
      'Sliema',
      'Swieqi',
      'Ta’ Xbiex',
      'Tarxien',
      'Valletta',
      'Xagħra',
      'Xewkija',
      'Żebbuġ Gozo',
      'Żebbuġ Malta',
      'Żejtun',
      'Żurrieq'
    ],
    'Marshall Islands': [
      'Ailinglaplap',
      'Ailuk',
      'Arno',
      'Aur',
      'Ebon',
      'Enewetak',
      'Jabat',
      'Jaluit',
      'Kili',
      'Kwajalein',
      'Lae',
      'Lib',
      'Likiep',
      'Majuro',
      'Maloelap',
      'Mejit',
      'Mili',
      'Namdrik',
      'Namu',
      'Rongelap',
      'Ujae',
      'Utrik',
      'Wotho',
      'Wotje'
    ],
    'Mauritania': [
      'Adrar',
      'Assaba',
      'Brakna',
      'Dakhlet Nouadhibou',
      'Gorgol',
      'Guidimaka',
      'Hodh Ech Chargui',
      'Hodh El Gharbi',
      'Inchiri',
      'Nouakchott Nord',
      'Nouakchott Ouest',
      'Nouakchott Sud',
      'Tagant',
      'Tiris Zemmour',
      'Trarza'
    ],
    'Mauritius': [
      'Agaléga',
      'Black River',
      'Cargados Carajos',
      'Flacq',
      'Grand Port',
      'Moka',
      'Pamplemousses',
      'Plaines Wilhems',
      'Port Louis',
      'Rivière du Rempart',
      'Rodrigues',
      'Savanne'
    ],
    'Mexico': [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Coahuila',
      'Colima',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'Mexico City',
      'Mexico State',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas'
    ],
    'Micronesia': ['Chuuk', 'Kosrae', 'Pohnpei', 'Yap'],
    'Moldova': [
      'Anenii Noi',
      'Basarabeasca',
      'Briceni',
      'Cahul',
      'Călărași',
      'Căușeni',
      'Cimișlia',
      'Criuleni',
      'Dondușeni',
      'Drochia',
      'Dubăsari',
      'Edineț',
      'Fălești',
      'Florești',
      'Glodeni',
      'Hîncești',
      'Ialoveni',
      'Leova',
      'Nisporeni',
      'Ocnița',
      'Orhei',
      'Rezina',
      'Rîșcani',
      'Sîngerei',
      'Soroca',
      'Strășeni',
      'Șoldănești',
      'Ștefan Vodă',
      'Taraclia',
      'Telenești',
      'Ungheni',
      'Chișinău',
      'Bălți',
      'Bender',
      'Gagauzia',
      'Transnistria'
    ],
    'Monaco': [], // No first-level administrative divisions
    'Mongolia': [
      'Arkhangai',
      'Bayan-Ölgii',
      'Bayankhongor',
      'Bulgan',
      'Darkhan-Uul',
      'Dornod',
      'Dornogovi',
      'Dundgovi',
      'Govi-Altai',
      'Govisümber',
      'Khentii',
      'Khovd',
      'Khövsgöl',
      'Ömnögovi',
      'Orkhon',
      'Övörkhangai',
      'Selenge',
      'Sükhbaatar',
      'Töv',
      'Uvs',
      'Zavkhan',
      'Ulaanbaatar'
    ],
    'Montenegro': [
      'Andrijevica',
      'Bar',
      'Berane',
      'Bijelo Polje',
      'Budva',
      'Cetinje',
      'Danilovgrad',
      'Gusinje',
      'Herceg Novi',
      'Kolašin',
      'Kotor',
      'Mojkovac',
      'Nikšić',
      'Plav',
      'Pljevlja',
      'Plužine',
      'Podgorica',
      'Rožaje',
      'Šavnik',
      'Tivat',
      'Ulcinj',
      'Žabljak'
    ],
    'Morocco': [
      'Béni Mellal-Khénifra',
      'Casablanca-Settat',
      'Drâa-Tafilalet',
      'Fès-Meknès',
      'Guelmim-Oued Noun',
      'Laâyoune-Sakia El Hamra',
      'Marrakech-Safi',
      'Oriental',
      'Rabat-Salé-Kénitra',
      'Souss-Massa',
      'Tanger-Tétouan-Al Hoceïma',
      'Dakhla-Oued Ed-Dahab'
    ],
    'Mozambique': [
      'Cabo Delgado',
      'Gaza',
      'Inhambane',
      'Manica',
      'Maputo',
      'Maputo City',
      'Nampula',
      'Niassa',
      'Sofala',
      'Tete',
      'Zambézia'
    ],
    'Myanmar': [
      'Ayeyarwady',
      'Bago',
      'Chin',
      'Kachin',
      'Kayah',
      'Kayin',
      'Magway',
      'Mandalay',
      'Mon',
      'Rakhine',
      'Sagaing',
      'Shan',
      'Tanintharyi',
      'Yangon',
      'Naypyidaw',
      'Kachin Self-Administered Zone',
      'Kaya Self-Administered Zone',
      'Palaung Self-Administered Zone',
      'Pa-O Self-Administered Zone',
      'Wa Self-Administered Division'
    ],
    'Namibia': [
      'Erongo',
      'Hardap',
      'Karas',
      'Kavango East',
      'Kavango West',
      'Khomas',
      'Kunene',
      'Ohangwena',
      'Omaheke',
      'Omusati',
      'Oshana',
      'Oshikoto',
      'Otjozondjupa',
      'Zambezi'
    ],
    'Nauru': [
      'Aiwo',
      'Anabar',
      'Anibare',
      'Baitsi',
      'Boe',
      'Buada',
      'Denigomodu',
      'Ewa',
      'Ijuw',
      'Meneng',
      'Nibok',
      'Uaboe',
      'Yaren'
    ],
    'Nepal': [
      'Bagmati',
      'Gandaki',
      'Karnali',
      'Koshi',
      'Lumbini',
      'Madhesh',
      'Sudurpashchim'
    ],
    'Netherlands': [
      'Drenthe',
      'Flevoland',
      'Friesland',
      'Gelderland',
      'Groningen',
      'Limburg',
      'North Brabant',
      'North Holland',
      'Overijssel',
      'South Holland',
      'Utrecht',
      'Zeeland'
    ],
    'New Zealand': [
      'Auckland',
      'Bay of Plenty',
      'Canterbury',
      'Gisborne',
      'Hawke’s Bay',
      'Manawatu-Wanganui',
      'Marlborough',
      'Nelson',
      'Northland',
      'Otago',
      'Southland',
      'Taranaki',
      'Tasman',
      'Waikato',
      'Wellington',
      'West Coast',
      'Chatham Islands'
    ],
    'Nicaragua': [
      'Boaco',
      'Carazo',
      'Chinandega',
      'Chontales',
      'Estelí',
      'Granada',
      'Jinotega',
      'León',
      'Madriz',
      'Managua',
      'Masaya',
      'Matagalpa',
      'Nueva Segovia',
      'Río San Juan',
      'Rivas',
      'North Caribbean Coast',
      'South Caribbean Coast'
    ],
    'Niger': [
      'Agadez',
      'Diffa',
      'Dosso',
      'Maradi',
      'Niamey',
      'Tahoua',
      'Tillabéri',
      'Zinder'
    ],
    'Nigeria': [
      'Abia',
      'Adamawa',
      'Akwa Ibom',
      'Anambra',
      'Bauchi',
      'Bayelsa',
      'Benue',
      'Borno',
      'Cross River',
      'Delta',
      'Ebonyi',
      'Edo',
      'Ekiti',
      'Enugu',
      'Federal Capital Territory',
      'Gombe',
      'Imo',
      'Jigawa',
      'Kaduna',
      'Kano',
      'Katsina',
      'Kebbi',
      'Kogi',
      'Kwara',
      'Lagos',
      'Nasarawa',
      'Niger',
      'Ogun',
      'Ondo',
      'Osun',
      'Oyo',
      'Plateau',
      'Rivers',
      'Sokoto',
      'Taraba',
      'Yobe',
      'Zamfara'
    ],
    'North Korea': [
      'Chagang',
      'North Hamgyong',
      'South Hamgyong',
      'North Hwanghae',
      'South Hwanghae',
      'Kangwon',
      'North Pyongan',
      'South Pyongan',
      'Ryanggang',
      'Pyongyang',
      'Rason',
      'Kaesong'
    ],
    'North Macedonia': [
      'Berovo',
      'Bitola',
      'Bogdanci',
      'Bogovinje',
      'Bosilovo',
      'Brvenica',
      'Centar',
      'Centar Župa',
      'Čaška',
      'Češinovo-Obleševo',
      'Čučer-Sandevo',
      'Debar',
      'Debarca',
      'Delčevo',
      'Demir Hisar',
      'Demir Kapija',
      'Dolneni',
      'Gazi Baba',
      'Gevgelija',
      'Gostivar',
      'Gradsko',
      'Ilinden',
      'Jegunovce',
      'Karbinci',
      'Karpoš',
      'Kavadarci',
      'Kičevo',
      'Kisela Voda',
      'Kočani',
      'Konče',
      'Kratovo',
      'Kriva Palanka',
      'Krivogaštani',
      'Kruševo',
      'Kumanovo',
      'Lipkovo',
      'Lozovo',
      'Makedonska Kamenica',
      'Makedonski Brod',
      'Mavrovo and Rostuša',
      'Negotino',
      'Novaci',
      'Novo Selo',
      'Ohrid',
      'Petrovec',
      'Plasnica',
      'Prilep',
      'Probištip',
      'Radoviš',
      'Rankovce',
      'Rosoman',
      'Saraj',
      'Sopište',
      'Star Dojran',
      'Staro Nagoričane',
      'Struga',
      'Strumica',
      'Studeničani',
      'Štip',
      'Sveti Nikole',
      'Tearce',
      'Tetovo',
      'Valandovo',
      'Vasilevo',
      'Veles',
      'Vevčani',
      'Vinica',
      'Vrapčište',
      'Zelenikovo',
      'Želino',
      'Zrnovci',
      'Skopje'
    ],
    'Norway': [
      'Agder',
      'Innlandet',
      'Møre og Romsdal',
      'Nordland',
      'Oslo',
      'Rogaland',
      'Troms og Finnmark',
      'Trøndelag',
      'Vestfold og Telemark',
      'Vestland',
      'Viken'
    ],
    'Oman': [
      'Ad Dakhiliyah',
      'Ad Dhahirah',
      'Al Batinah North',
      'Al Batinah South',
      'Al Buraimi',
      'Al Wusta',
      'Dhofar',
      'Musandam',
      'Muscat',
      'Northeast',
      'South Sharqiyah'
    ],
    'Pakistan': [
      'Balochistan',
      'Khyber Pakhtunkhwa',
      'Punjab',
      'Sindh',
      'Azad Jammu and Kashmir',
      'Gilgit-Baltistan',
      'Islamabad Capital Territory'
    ],
    'Palau': [
      'Aimeliik',
      'Airai',
      'Angaur',
      'Hatohobei',
      'Kayangel',
      'Koror',
      'Melekeok',
      'Ngaraard',
      'Ngarchelong',
      'Ngardmau',
      'Ngatpang',
      'Ngchesar',
      'Ngeremlengui',
      'Ngiwal',
      'Peleliu',
      'Sonsorol'
    ],
    'Palestine': [
      'Bethlehem',
      'Deir al Balah',
      'Gaza',
      'Hebron',
      'Jenin',
      'Jericho and Al Aghwar',
      'Jerusalem',
      'Khan Yunis',
      'Nablus',
      'North Gaza',
      'Qalqilya',
      'Rafah',
      'Ramallah and Al Bireh',
      'Salfit',
      'Tubas',
      'Tulkarm'
    ],
    'Panama': [
      'Bocas del Toro',
      'Chiriquí',
      'Coclé',
      'Colón',
      'Darién',
      'Emberá',
      'Guna Yala',
      'Herrera',
      'Los Santos',
      'Ngäbe-Buglé',
      'Panamá',
      'Panamá Oeste',
      'Veraguas'
    ],
    'Papua New Guinea': [
      'Bougainville',
      'Central',
      'Chimbu',
      'Eastern Highlands',
      'East New Britain',
      'East Sepik',
      'Enga',
      'Gulf',
      'Hela',
      'Jiwaka',
      'Madang',
      'Manus',
      'Milne Bay',
      'Morobe',
      'National Capital District',
      'New Ireland',
      'Northern',
      'Southern Highlands',
      'West New Britain',
      'Western',
      'Western Highlands',
      'West Sepik'
    ],
    'Paraguay': [
      'Alto Paraguay',
      'Alto Paraná',
      'Amambay',
      'Asunción',
      'Boquerón',
      'Caaguazú',
      'Caazapá',
      'Canindeyú',
      'Central',
      'Concepción',
      'Cordillera',
      'Guairá',
      'Itapúa',
      'Misiones',
      'Ñeembucú',
      'Paraguarí',
      'Presidente Hayes',
      'San Pedro'
    ],
    'Peru': [
      'Amazonas',
      'Áncash',
      'Apurímac',
      'Arequipa',
      'Ayacucho',
      'Cajamarca',
      'Callao',
      'Cusco',
      'Huancavelica',
      'Huánuco',
      'Ica',
      'Junín',
      'La Libertad',
      'Lambayeque',
      'Lima',
      'Loreto',
      'Madre de Dios',
      'Moquegua',
      'Pasco',
      'Piura',
      'Puno',
      'San Martín',
      'Tacna',
      'Tumbes',
      'Ucayali'
    ],
    'Philippines': [
      'Abra',
      'Agusan del Norte',
      'Agusan del Sur',
      'Aklan',
      'Albay',
      'Antique',
      'Apayao',
      'Aurora',
      'Basilan',
      'Bataan',
      'Batanes',
      'Batangas',
      'Benguet',
      'Biliran',
      'Bohol',
      'Bukidnon',
      'Bulacan',
      'Cagayan',
      'Camarines Norte',
      'Camarines Sur',
      'Camiguin',
      'Capiz',
      'Catanduanes',
      'Cavite',
      'Cebu',
      'Cotabato',
      'Davao de Oro',
      'Davao del Norte',
      'Davao del Sur',
      'Davao Occidental',
      'Davao Oriental',
      'Dinagat Islands',
      'Eastern Samar',
      'Guimaras',
      'Ifugao',
      'Ilocos Norte',
      'Ilocos Sur',
      'Iloilo',
      'Isabela',
      'Kalinga',
      'La Union',
      'Laguna',
      'Lanao del Norte',
      'Lanao del Sur',
      'Leyte',
      'Maguindanao del Norte',
      'Maguindanao del Sur',
      'Marinduque',
      'Masbate',
      'Misamis Occidental',
      'Misamis Oriental',
      'Mountain Province',
      'Negros Occidental',
      'Negros Oriental',
      'Northern Samar',
      'Nueva Ecija',
      'Nueva Vizcaya',
      'Occidental Mindoro',
      'Oriental Mindoro',
      'Palawan',
      'Pampanga',
      'Pangasinan',
      'Quezon',
      'Quirino',
      'Rizal',
      'Romblon',
      'Samar',
      'Sarangani',
      'Siquijor',
      'Sorsogon',
      'South Cotabato',
      'Southern Leyte',
      'Sultan Kudarat',
      'Sulu',
      'Surigao del Norte',
      'Surigao del Sur',
      'Tarlac',
      'Tawi-Tawi',
      'Zambales',
      'Zamboanga del Norte',
      'Zamboanga del Sur',
      'Zamboanga Sibugay',
      'Metro Manila'
    ],
    'Poland': [
      'Greater Poland',
      'Kuyavian-Pomeranian',
      'Lesser Poland',
      'Łódź',
      'Lower Silesian',
      'Lublin',
      'Lubusz',
      'Masovian',
      'Opole',
      'Podkarpackie',
      'Podlaskie',
      'Pomeranian',
      'Silesian',
      'Świętokrzyskie',
      'Warmian-Masurian',
      'West Pomeranian'
    ],
    'Portugal': [
      'Aveiro',
      'Beja',
      'Braga',
      'Bragança',
      'Castelo Branco',
      'Coimbra',
      'Évora',
      'Faro',
      'Guarda',
      'Leiria',
      'Lisbon',
      'Portalegre',
      'Porto',
      'Santarém',
      'Setúbal',
      'Viana do Castelo',
      'Vila Real',
      'Viseu',
      'Azores',
      'Madeira'
    ],
    'Qatar': [
      'Ad Dawhah',
      'Al Khawr wa adh Dhakhirah',
      'Al Wakrah',
      'Ar Rayyan',
      'Ash Shamal',
      'Az Za’ayin',
      'Umm Salal'
    ],
    'Republic of the Congo': [
      'Bouenza',
      'Brazzaville',
      'Cuvette',
      'Cuvette-Ouest',
      'K'
    ],
  };

  static List<String> getCountries() {
    return countryStateMap.keys.toList()..sort();
  }

  static List<String> getStates(String country) {
    return countryStateMap[country] ?? [];
  }
}
